name: eks

on:
  workflow_dispatch:
  

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      # pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::185348645972:role/github-aws-connector
          aws-region: ap-south-1  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 
     
      - name: Initialize Terraform
        run: terraform init


      - name: Apply Terraform plan
        run: terraform apply -auto-approve

    
