
name: Deploy to EKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::185348645972:role/github-aws-connector
        aws-region: ap-south-1

    
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1
     with:
       terraform_version: 1.0.0 
          
    # Terraform apply (creates/updates cluster + nodegroups)
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    # Update kubeconfig for EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name my-eks-cluster 

    # Deploy existing ECR image to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f eks/deployment.yaml
